"use client";

import { useState, type CSSProperties, type ReactNode } from "react";

import {
  type AssetDocument,
  type AssetRecord,
  type LineRecord,
  type PlantRegister,
  type WorkOrder,
} from "@/lib/canvas/engineering";
import { workOrderDetail } from "@/lib/canvas/documents";
import type { DrawingNode } from "@/lib/canvas/model";

import styles from "./AssetPanels.module.css";

/**
 * The asset views: the popover on the drawing and the context row beneath it.
 *
 * Everything here renders the plant register. Values that come from the register rather
 * than the corpus carry a "Simulated" mark at the level of the panel that shows them, so an
 * engineer can use the screen as it is meant to be used without mistaking a generated trend
 * or work order for plant data.
 */

// ────────────────────────────────────────────────────────────────────────────────────────────
// Shared
// ────────────────────────────────────────────────────────────────────────────────────────────

/** Marks a panel whose contents come from the simulated register. */
export function SimulatedBadge({ label = "Simulated" }: { readonly label?: string }) {
  return (
    <span
      className={styles.simulated}
      title="Generated by the workspace register for demonstration. Not plant data."
    >
      {label}
    </span>
  );
}

const STATUS_CLASS: Record<string, string | undefined> = {
  "In service": styles.statusOk,
  Standby: styles.statusWarn,
  "Under maintenance": styles.statusBad,
  Open: styles.statusBad,
  "In progress": styles.statusWarn,
  Planned: styles.statusInfo,
  Closed: styles.statusOk,
  High: styles.statusBad,
  Medium: styles.statusWarn,
  Low: styles.statusOk,
};

/** A status word in a coloured chip. The word always carries the meaning; colour repeats it. */
export function StatusChip({ value }: { readonly value: string }) {
  return (
    <span className={`${styles.chip} ${STATUS_CLASS[value] ?? ""}`}>
      <i aria-hidden="true" />
      {value}
    </span>
  );
}

function PanelShell({
  title,
  icon,
  badge,
  action,
  children,
}: {
  readonly title: string;
  readonly icon: ReactNode;
  readonly badge?: ReactNode;
  readonly action?: ReactNode;
  readonly children: ReactNode;
}) {
  return (
    <section className={styles.panel}>
      <header>
        <h2>
          {icon}
          {title}
        </h2>
        {badge}
        {action ? <span className={styles.headerAction}>{action}</span> : null}
      </header>
      <div className={styles.panelBody}>{children}</div>
    </section>
  );
}

// ────────────────────────────────────────────────────────────────────────────────────────────
// Popover
// ────────────────────────────────────────────────────────────────────────────────────────────

/** The symbol as drawn, cropped out of the real sheet. The one image here that is not simulated. */
function SymbolCrop({
  node,
  imageUrl,
  sheet,
}: {
  readonly node: DrawingNode;
  readonly imageUrl: string;
  readonly sheet: { readonly width: number; readonly height: number };
}) {
  const view = 104;
  // Frame a little context around the symbol so its connections are visible too.
  const span = Math.max(node.width, node.height, 24) * 3.2;
  const scale = view / span;
  const style: CSSProperties = {
    backgroundImage: `url("${imageUrl}")`,
    backgroundSize: `${sheet.width * scale}px ${sheet.height * scale}px`,
    backgroundPosition: `${-(node.x - span / 2) * scale}px ${-(node.y - span / 2) * scale}px`,
  };
  return (
    <figure className={styles.crop}>
      <div style={style} role="img" aria-label="Symbol as drawn on the sheet" />
      <figcaption>As drawn</figcaption>
    </figure>
  );
}

export function AssetPopover({
  node,
  asset,
  line,
  printedTag,
  className,
  imageUrl,
  sheet,
  joined,
  register,
  onSelectNode,
  onViewAsset,
  onShowRelated,
  onReadTag,
  onAsk,
  onDismiss,
}: {
  readonly node: DrawingNode;
  readonly asset?: AssetRecord | undefined;
  readonly line?: LineRecord | undefined;
  readonly printedTag?: string | undefined;
  readonly className: string;
  readonly imageUrl: string;
  readonly sheet: { readonly width: number; readonly height: number };
  readonly joined: readonly { readonly id: string; readonly hops: number }[];
  readonly register: PlantRegister;
  readonly onSelectNode: (id: string) => void;
  readonly onViewAsset: () => void;
  readonly onShowRelated: () => void;
  readonly onReadTag: () => void;
  readonly onAsk: () => void;
  readonly onDismiss: () => void;
}) {
  // A pipe-run selection: a connector or crossing is part of a line, and the line is what an
  // engineer means when they click on pipework.
  if (!asset && line) {
    return (
      <div className={styles.popover} aria-hidden="true">
        <header>
          <div>
            <strong>{line.number}</strong>
            <p>
              Pipe run · {line.sizeInches}&quot; {line.service.name}
            </p>
          </div>
          <button type="button" tabIndex={-1} onClick={onDismiss} aria-label="Close">
            ✕
          </button>
        </header>
        <div className={styles.popoverTop}>
          <SymbolCrop node={node} imageUrl={imageUrl} sheet={sheet} />
          <dl className={styles.facts}>
            <div>
              <dt>Nominal size</dt>
              <dd>{line.sizeInches}&quot;</dd>
            </div>
            <div>
              <dt>Service</dt>
              <dd>
                {line.service.code} · {line.service.name}
              </dd>
            </div>
            <div>
              <dt>Piping class</dt>
              <dd>{line.pipeClass}</dd>
            </div>
            <div>
              <dt>Components</dt>
              <dd>{line.assets.length}</dd>
            </div>
          </dl>
        </div>
        {line.assets.length > 0 && (
          <div className={styles.tagCloud}>
            {line.assets.slice(0, 18).map((id) => (
              <button key={id} type="button" tabIndex={-1} onClick={() => onSelectNode(id)}>
                {register.assets.get(id)?.tag ?? id}
              </button>
            ))}
            {line.assets.length > 18 ? <span>+{line.assets.length - 18}</span> : null}
          </div>
        )}
        <footer>
          <SimulatedBadge label="Simulated line number" />
          <button type="button" tabIndex={-1} onClick={onAsk}>
            Ask about this line
          </button>
        </footer>
      </div>
    );
  }

  const tag = printedTag ?? asset?.tag ?? node.id;
  const openOrders = asset?.workOrders.filter((w) => w.status !== "Closed").length ?? 0;
  const lineNumber = asset?.lines[0]
    ? register.lines.get(asset.lines[0])?.number
    : undefined;
  const loopPartner = asset?.loop
    ? [...register.assets.values()].find(
        (a) => a.loop === asset.loop && a.tag !== asset.tag,
      )
    : undefined;

  return (
    <div className={styles.popover} aria-hidden="true">
      <header>
        <div>
          <strong>{tag}</strong>
          <p>{asset?.name ?? className}</p>
        </div>
        <button type="button" tabIndex={-1} onClick={onDismiss} aria-label="Close">
          ✕
        </button>
      </header>
      <div className={styles.popoverTop}>
        <SymbolCrop node={node} imageUrl={imageUrl} sheet={sheet} />
        <div className={styles.popoverSummary}>
          {asset ? <StatusChip value={asset.status} /> : null}
          <dl className={styles.facts}>
            <div>
              <dt>Type</dt>
              <dd>{asset?.name ?? className}</dd>
            </div>
            <div>
              <dt>Area</dt>
              <dd>
                {register.area} · {register.service.code}
              </dd>
            </div>
            {lineNumber ? (
              <div>
                <dt>Line</dt>
                <dd>{lineNumber}</dd>
              </div>
            ) : null}
            {asset?.loop ? (
              <div>
                <dt>Loop</dt>
                <dd>
                  {asset.loop}
                  {loopPartner ? ` · ${loopPartner.tag}` : ""}
                </dd>
              </div>
            ) : null}
            <div>
              <dt>Connected</dt>
              <dd>
                {joined.length} {joined.length === 1 ? "component" : "components"}
              </dd>
            </div>
            <div>
              <dt>Open WOs</dt>
              <dd className={openOrders ? styles.alert : undefined}>{openOrders}</dd>
            </div>
          </dl>
        </div>
      </div>
      {printedTag ? (
        <p className={styles.provenance}>Tag read from the drawing</p>
      ) : (
        <p className={styles.provenance}>
          <SimulatedBadge label="Simulated tag" /> Source node {node.id}
        </p>
      )}
      <footer>
        <button type="button" tabIndex={-1} onClick={onViewAsset}>
          View asset
        </button>
        <button type="button" tabIndex={-1} onClick={onShowRelated}>
          Show related
        </button>
        {!printedTag ? (
          <button type="button" tabIndex={-1} onClick={onReadTag}>
            Read printed tag
          </button>
        ) : null}
        <button
          type="button"
          tabIndex={-1}
          className={styles.primaryAction}
          onClick={onAsk}
        >
          Ask agent
        </button>
      </footer>
    </div>
  );
}

// ────────────────────────────────────────────────────────────────────────────────────────────
// Hierarchy, files, work orders, summary
// ────────────────────────────────────────────────────────────────────────────────────────────

export function HierarchyPanel({
  register,
  sheet,
  tag,
  name,
  lineNumber,
  onSite,
  onArea,
  onSystem,
  onLine,
  onTag,
}: {
  readonly register: PlantRegister;
  readonly sheet: string;
  readonly tag: string;
  readonly name: string;
  readonly lineNumber?: string | undefined;
  readonly onSite: () => void;
  readonly onArea: () => void;
  readonly onSystem: () => void;
  readonly onLine?: (() => void) | undefined;
  readonly onTag: () => void;
}) {
  const levels: {
    label: string;
    hint: string;
    count?: string;
    onClick?: (() => void) | undefined;
  }[] = [
    { label: register.site, hint: "Open the source library", onClick: onSite },
    {
      label: `${register.area} · ${register.unit}`,
      hint: "Browse every tagged component in this unit",
      count: `${register.assets.size} tags`,
      onClick: onArea,
    },
    {
      label: register.system,
      hint: "Show the pipe runs of this system on the drawing",
      count: `${register.lines.size} runs`,
      onClick: onSystem,
    },
    { label: sheet, hint: "Open the source drawing", onClick: onSite },
    ...(lineNumber
      ? [{ label: lineNumber, hint: "Trace this line on the drawing", onClick: onLine }]
      : []),
  ];
  return (
    <PanelShell title="Asset hierarchy" icon={<TreeIcon />} badge={<SimulatedBadge />}>
      <ol className={styles.tree}>
        {levels.map((level, depth) => (
          <li key={level.hint} style={{ "--depth": depth } as CSSProperties}>
            {level.onClick ? (
              <button onClick={level.onClick} title={level.hint}>
                {level.label}
                {level.count ? <em>{level.count}</em> : null}
              </button>
            ) : (
              <span title={level.hint}>{level.label}</span>
            )}
          </li>
        ))}
        <li
          style={{ "--depth": levels.length } as CSSProperties}
          className={styles.treeLeaf}
        >
          <button onClick={onTag} title="Show on the drawing">
            <strong>{tag}</strong>
            <small>{name}</small>
          </button>
        </li>
      </ol>
    </PanelShell>
  );
}

export function FilesPanel({
  asset,
  onOpen,
}: {
  readonly asset?: AssetRecord | undefined;
  readonly onOpen: (document: AssetDocument) => void;
}) {
  const documents = asset?.documents ?? [];
  return (
    <PanelShell
      title={`Related files${documents.length ? ` (${documents.length})` : ""}`}
      icon={<FileIcon />}
      badge={<SimulatedBadge />}
    >
      {documents.length === 0 ? (
        <p className={styles.quiet}>Select a component to list its documentation.</p>
      ) : (
        <ul className={styles.files}>
          {documents.map((document) => (
            <li key={document.name}>
              <button
                className={styles.fileRow}
                onClick={() => onOpen(document)}
                title={`Open ${document.name}`}
              >
                <span className={styles.fileIcon} data-format={document.format}>
                  {document.format}
                </span>
                <span className={styles.fileText}>
                  <strong>{document.name}</strong>
                  <small>
                    {document.kind}
                    {document.simulated
                      ? ` · ${(document.sizeKb / 1024).toFixed(1)} MB`
                      : " · source drawing"}
                  </small>
                </span>
                <time>{document.date || "Corpus"}</time>
              </button>
            </li>
          ))}
        </ul>
      )}
    </PanelShell>
  );
}

const NEXT_STATUS: Partial<
  Record<WorkOrder["status"], readonly [WorkOrder["status"], string]>
> = {
  Planned: ["Open", "Release"],
  Open: ["In progress", "Start work"],
  "In progress": ["Closed", "Complete"],
  Closed: ["Open", "Reopen"],
};

export function WorkOrdersPanel({
  asset,
  onOpenDocument,
  onAsk,
}: {
  readonly asset?: AssetRecord | undefined;
  readonly onOpenDocument: (document: AssetDocument) => void;
  readonly onAsk: (question: string) => void;
}) {
  // Status changes made here, by order id. They last for the session, across selections.
  const [statuses, setStatuses] = useState<ReadonlyMap<string, WorkOrder["status"]>>(
    new Map(),
  );
  const [expanded, setExpanded] = useState<string>();
  const orders = (asset?.workOrders ?? []).map((order) => ({
    ...order,
    status: statuses.get(order.id) ?? order.status,
  }));
  const open = orders.filter((order) => order.status !== "Closed").length;
  return (
    <PanelShell
      title={`Work orders (${orders.length})`}
      icon={<WrenchIcon />}
      badge={<SimulatedBadge />}
      action={open ? <span className={styles.count}>{open} open</span> : undefined}
    >
      {orders.length === 0 || !asset ? (
        <p className={styles.quiet}>
          No work orders recorded against {asset?.tag ?? "this component"}.
        </p>
      ) : (
        <ul className={styles.orders} tabIndex={0} aria-label="Work orders">
          {orders.map((order) => {
            const isOpen = expanded === order.id;
            const detail = isOpen ? workOrderDetail(order, asset) : undefined;
            const next = NEXT_STATUS[order.status];
            return (
              <li key={order.id} data-expanded={isOpen || undefined}>
                <button
                  className={styles.orderToggle}
                  aria-expanded={isOpen}
                  onClick={() => setExpanded(isOpen ? undefined : order.id)}
                >
                  <span className={styles.orderHead}>
                    <strong>{order.id}</strong>
                    <StatusChip value={order.status} />
                  </span>
                  <span className={styles.orderTitle}>{order.title}</span>
                  <span className={styles.orderMeta}>
                    <StatusChip value={order.priority} />
                    <span>
                      {order.type} · {order.failureCode} · due {order.due}
                    </span>
                  </span>
                </button>
                {detail && (
                  <div className={styles.orderDetail}>
                    <p>
                      <b>Symptom</b> {detail.symptom}
                    </p>
                    <p>
                      <b>Failure mode</b> {detail.failure}
                    </p>
                    <p>
                      <b>Permit</b> {detail.permit}
                    </p>
                    <ol>
                      {detail.tasks.map((task) => (
                        <li key={task}>{task}</li>
                      ))}
                    </ol>
                    <div className={styles.orderDocs}>
                      {detail.documents.map((document) => (
                        <button
                          key={document.name}
                          onClick={() => onOpenDocument(document)}
                        >
                          {document.kind}
                        </button>
                      ))}
                    </div>
                    <div className={styles.orderActions}>
                      {next && (
                        <button
                          className={styles.orderPrimary}
                          onClick={() =>
                            setStatuses((current) =>
                              new Map(current).set(order.id, next[0]),
                            )
                          }
                        >
                          {next[1]}
                        </button>
                      )}
                      <button
                        onClick={() =>
                          onAsk(
                            `Work order ${order.id} on ${asset.tag} (${asset.name}): "${order.title}", failure mode ${detail.failure}. From the drawing, what must be isolated to do this work safely, what else loses service while it is out, and what should be checked first?`,
                          )
                        }
                      >
                        Ask agent
                      </button>
                    </div>
                  </div>
                )}
              </li>
            );
          })}
        </ul>
      )}
    </PanelShell>
  );
}

export type SummaryTarget = "components" | "loops" | "lines" | "tags" | "coverage";

export function SummaryPanel({
  register,
  drawingNodes,
  positioned,
  printedTags,
  onOpen,
}: {
  readonly register: PlantRegister;
  readonly drawingNodes: number;
  readonly positioned: number;
  readonly printedTags: number;
  readonly onOpen: (target: SummaryTarget) => void;
}) {
  const counts = new Map<string, number>();
  for (const asset of register.assets.values()) {
    counts.set(asset.category, (counts.get(asset.category) ?? 0) + 1);
  }
  const instruments = counts.get("instrument") ?? 0;
  const valves =
    (counts.get("control-valve") ?? 0) +
    (counts.get("hand-valve") ?? 0) +
    (counts.get("safety-valve") ?? 0);
  const equipment =
    (counts.get("vessel") ?? 0) +
    (counts.get("exchanger") ?? 0) +
    (counts.get("pump") ?? 0);
  const coverage = drawingNodes ? Math.round((positioned / drawingNodes) * 100) : 0;
  const rows: [SummaryTarget, string, string, string, boolean][] = [
    [
      "components",
      String(register.assets.size),
      "Tagged components",
      `${instruments} instruments · ${valves} valves · ${equipment} equipment`,
      true,
    ],
    [
      "loops",
      String(register.controlLoops),
      "Control loops",
      "Transmitter paired with its final element",
      true,
    ],
    [
      "lines",
      String(register.lines.size),
      "Pipe runs",
      `${register.service.name} service`,
      true,
    ],
    [
      "tags",
      String(printedTags),
      "Printed tags read",
      printedTags
        ? "Confirmed from the drawing by the agent"
        : "Not read yet — ask the agent to read them",
      printedTags > 0,
    ],
    [
      "coverage",
      `${coverage}%`,
      "Diagram coverage",
      "Symbols with drawable positions",
      coverage === 100,
    ],
  ];
  return (
    <PanelShell title="Plant context summary" icon={<GridIcon />}>
      <ul className={styles.summary}>
        {rows.map(([target, value, label, detail, done]) => (
          <li key={label}>
            <button onClick={() => onOpen(target)}>
              <span
                className={styles.check}
                data-pending={!done || undefined}
                aria-hidden="true"
              >
                {done ? "✓" : "!"}
              </span>
              <strong>{value}</strong>
              <span className={styles.summaryText}>
                <span>{label}</span>
                <small>{detail}</small>
              </span>
              <span className={styles.chevron} aria-hidden="true">
                ›
              </span>
            </button>
          </li>
        ))}
      </ul>
    </PanelShell>
  );
}

/** ISO 14224 failure modes for the selected asset, ranked by the register's likelihood. */
export function FailureModes({ asset }: { readonly asset?: AssetRecord | undefined }) {
  if (!asset || asset.failureModes.length === 0) return null;
  const order = { High: 0, Medium: 1, Low: 2 } as const;
  const ranked = [...asset.failureModes].sort(
    (a, b) => order[a.likelihood] - order[b.likelihood],
  );
  return (
    <ul className={styles.failures}>
      {ranked.map((mode) => (
        <li key={mode.code}>
          <code>{mode.code}</code>
          <div>
            <strong>{mode.name}</strong>
            <small>{mode.indicator}</small>
          </div>
          <StatusChip value={mode.likelihood} />
        </li>
      ))}
    </ul>
  );
}

// ────────────────────────────────────────────────────────────────────────────────────────────
// Icons: small, stroke-only, currentColor, to match the rest of the canvas
// ────────────────────────────────────────────────────────────────────────────────────────────

function Svg({ children }: { readonly children: ReactNode }) {
  return (
    <svg
      width="14"
      height="14"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      aria-hidden="true"
    >
      {children}
    </svg>
  );
}

const TreeIcon = () => (
  <Svg>
    <rect x="3" y="3" width="6" height="6" rx="1" />
    <rect x="15" y="15" width="6" height="6" rx="1" />
    <path d="M6 9v6a3 3 0 003 3h6" />
  </Svg>
);
const FileIcon = () => (
  <Svg>
    <path d="M14 3H7a2 2 0 00-2 2v14a2 2 0 002 2h10a2 2 0 002-2V8z" />
    <path d="M14 3v5h5" />
  </Svg>
);
const WrenchIcon = () => (
  <Svg>
    <path d="M14.7 6.3a4 4 0 00-5.4 5.4L3 18l3 3 6.3-6.3a4 4 0 005.4-5.4l-2.5 2.5-2.5-.5-.5-2.5z" />
  </Svg>
);
const GridIcon = () => (
  <Svg>
    <rect x="3" y="3" width="7" height="7" rx="1" />
    <rect x="14" y="3" width="7" height="7" rx="1" />
    <rect x="3" y="14" width="7" height="7" rx="1" />
    <rect x="14" y="14" width="7" height="7" rx="1" />
  </Svg>
);
