/** Stable delimiters around machine-supplied canvas metadata. */
export const ASSISTANT_CONTEXT_START = "<!-- pid-workspace-context:v1 -->";
export const ASSISTANT_CONTEXT_END = "<!-- /pid-workspace-context -->";

/**
 * Remove only a complete context suffix generated by the canvas.
 *
 * Requiring both a separator before the opening marker and the closing marker at the very
 * end prevents ordinary user text containing a marker-like string from being altered.
 */
export function stripWorkspaceContext(question: string): string {
  const start = question.lastIndexOf(`\n\n${ASSISTANT_CONTEXT_START}`);
  if (start < 0 || !question.endsWith(ASSISTANT_CONTEXT_END)) return question;
  return question.slice(0, start).trimEnd();
}
