"""Least-privilege function tools exposed to the P&ID Intelligence Agent.

These tools are the agent's entire privilege surface. Every one of them is read-only, and
each is narrow enough that its worst-case behaviour is stated in its own docstring. The
agent has no shell, no network reach, no file write, no delete, no SQL execution, no
environment access and no secret retrieval.

Tool argument schemas are generated by the Agents SDK from the Python signatures below. No
hand-authored domain schema is introduced, and every textual tool result is an ordinary
tool result string rather than a second API contract.
"""

from __future__ import annotations

from pid_intelligence.tools.corpus_tools import build_corpus_tools
from pid_intelligence.tools.graph_tools import build_graph_tools

__all__ = ["build_corpus_tools", "build_graph_tools"]
