"""Deterministic GraphML topology tools.

Connectivity questions are answered by graph code, not by asking the model to trace lines
across an image. These tools expose bounded, read-only operations over corpus GraphML and
return plain text; their argument schemas are generated by the Agents SDK from the Python
signatures below.

Every result states the graph's directedness and says explicitly when a bound truncated
it, so the agent can never mistake a partial neighbourhood for a complete one.
"""

from __future__ import annotations

import asyncio
from pathlib import Path

from agents import function_tool
from agents.tool import FunctionTool

from pid_intelligence.corpus.graphml import (
    DRAFTING_LABELS,
    EdgeRecord,
    EquipmentReach,
    GraphSummary,
    NeighborhoodResult,
    PathResult,
    SearchResult,
)
from pid_intelligence.corpus.paths import resolve_corpus_path
from pid_intelligence.corpus.services import CorpusServices
from pid_intelligence.observability.metrics import MetricsRegistry
from pid_intelligence.settings import Settings
from pid_intelligence.tools.corpus_tools import (
    ToolExecutionError,
    instrument_tool,
    tool_error_message,
)

__all__ = ["build_graph_tools"]


def build_graph_tools(
    settings: Settings,
    services: CorpusServices,
    metrics: MetricsRegistry,
) -> list[FunctionTool]:
    """Build the deterministic GraphML query tools.

    Args:
        settings: Validated configuration supplying the query bounds.
        services: Shared corpus services holding the parsed-graph cache.
        metrics: Registry receiving per-tool call, duration, error and result-size counts.

    Returns:
        The tool objects to register on the agent, in a stable order.
    """
    corpus_root = services.corpus_root
    graphs = services.graphs
    timeout = settings.tool_timeout_s

    def _resolve(path: str) -> Path:
        """Resolve a caller-supplied path and require it to be a GraphML artifact."""
        resolved = resolve_corpus_path(
            path,
            corpus_root=corpus_root,
            max_bytes=settings.max_corpus_file_bytes,
        )
        if resolved.suffix.lower() != ".graphml":
            raise ToolExecutionError(
                f"graph tools operate on .graphml artifacts; {resolved.name} is "
                f"{resolved.suffix.lower() or 'untyped'}"
            )
        return resolved

    @function_tool(timeout=timeout, failure_error_function=tool_error_message)
    async def graph_summary(path: str) -> str:
        """Describe a GraphML topology file before querying it.

        Run this first on any topology file. It reports whether the graph is directed,
        how large it is, which node and edge attributes exist, and which node labels are
        most common — which is what tells you whether the file models equipment, symbols,
        line segments or something else, and which attribute carries tag identity.

        Args:
            path: Corpus-relative path to a .graphml file, as listed by list_corpus_files.

        Returns:
            A plain-text summary of the graph's shape, attribute vocabulary and label
            distribution.
        """
        with instrument_tool(metrics, "graph_summary"):
            resolved = await asyncio.to_thread(_resolve, path)
            summary = await asyncio.to_thread(graphs.summary, resolved)
            return _render_summary(path, summary)

    @function_tool(timeout=timeout, failure_error_function=tool_error_message)
    async def graph_find_nodes(path: str, query: str, limit: int | None = None) -> str:
        """Resolve an asset, instrument or line identity to graph nodes.

        Use this to turn a tag or name from a drawing or from the user's question into
        concrete node identifiers before asking about connectivity. Matching is a
        case-insensitive substring test over node identifiers and over every string
        attribute, so a partial tag or a differently cased tag still resolves.

        If several nodes match a tag that should be unique, that ambiguity is itself a
        finding: report it rather than silently picking one.

        Args:
            path: Corpus-relative path to a .graphml file.
            query: Tag, name or fragment to resolve.
            limit: Maximum nodes to return.

        Returns:
            One node per line with its attributes, the total number of matches, and an
            explicit note when the returned set is truncated.
        """
        with instrument_tool(metrics, "graph_find_nodes"):
            resolved = await asyncio.to_thread(_resolve, path)
            result = await asyncio.to_thread(graphs.find_nodes, resolved, query, limit=limit)
            metrics.observe("graph_query_nodes_returned", float(len(result.nodes)))
            return _render_search(query, result)

    @function_tool(timeout=timeout, failure_error_function=tool_error_message)
    async def graph_neighbors(path: str, node: str, hops: int = 1) -> str:
        """List what a node is connected to, out to a bounded number of hops.

        This is the primary tool for "what is connected to X" questions. In a directed
        graph both upstream and downstream neighbours are reached, and each returned edge
        keeps its direction, so flow direction remains readable in the result.

        Start at one hop. Widen only when one hop does not answer the question, because
        each extra hop grows the result quickly and may hit the node budget.

        Args:
            path: Corpus-relative path to a .graphml file.
            node: Node identifier, ideally one returned by graph_find_nodes.
            hops: Radius of the expansion, in edges.

        Returns:
            The reached nodes with their hop distance, the edges among them, and an
            explicit statement when a budget truncated the expansion.
        """
        with instrument_tool(metrics, "graph_neighbors"):
            resolved = await asyncio.to_thread(_resolve, path)
            result = await asyncio.to_thread(graphs.neighbors, resolved, node, hops=hops)
            metrics.observe("graph_query_nodes_returned", float(len(result.nodes)))
            metrics.observe("graph_query_edges_returned", float(len(result.edges)))
            return _render_neighborhood(result)

    @function_tool(timeout=timeout, failure_error_function=tool_error_message)
    async def graph_connected_equipment(path: str, node: str, limit: int | None = None) -> str:
        """List the equipment and instruments a node is connected to on the drawing.

        Use this first for "what is X connected to". It walks through the drawing's
        line connectors, crossings and arrows and stops at the first real item on each
        path, so it returns the valves, instruments, vessels and pumps an engineer means
        by connected. graph_neighbors counts every connector as a hop and often reaches
        no equipment at all within its hop limit; do not conclude that nothing is
        connected from a graph_neighbors result.

        Args:
            path: Corpus-relative path to a .graphml file.
            node: Node identifier, ideally one returned by graph_find_nodes.
            limit: Most items to return.

        Returns:
            Each connected item with its class label and graph distance, nearest first,
            and an explicit statement when a bound truncated the walk.
        """
        with instrument_tool(metrics, "graph_connected_equipment"):
            resolved = await asyncio.to_thread(_resolve, path)
            result = await asyncio.to_thread(
                graphs.connected_equipment, resolved, node, limit=limit
            )
            metrics.observe("graph_query_nodes_returned", float(len(result.found)))
            return _render_equipment(result)

    @function_tool(timeout=timeout, failure_error_function=tool_error_message)
    async def graph_shortest_path(
        path: str,
        source: str,
        target: str,
        cutoff: int | None = None,
    ) -> str:
        """Determine whether and how two nodes are connected.

        Use this for "is X connected to Y" and "what runs between X and Y" questions. In a
        directed graph traversal honours edge direction, so a reported absence of a path
        is a statement about flow direction, not about the absence of any relationship —
        say so when reporting it.

        Args:
            path: Corpus-relative path to a .graphml file.
            source: Identifier of the start node.
            target: Identifier of the end node.
            cutoff: Maximum number of edges in the path.

        Returns:
            The node sequence and the edges traversed, or an explicit statement that no
            path exists within the cutoff.
        """
        with instrument_tool(metrics, "graph_shortest_path"):
            resolved = await asyncio.to_thread(_resolve, path)
            result = await asyncio.to_thread(
                graphs.shortest_path, resolved, source, target, cutoff=cutoff
            )
            metrics.observe("graph_query_nodes_returned", float(len(result.nodes)))
            metrics.observe("graph_query_edges_returned", float(len(result.edges)))
            return _render_path(result)

    @function_tool(timeout=timeout, failure_error_function=tool_error_message)
    async def graph_edge_lookup(
        path: str,
        source: str | None = None,
        target: str | None = None,
        limit: int | None = None,
    ) -> str:
        """Inspect the edges incident to a node, or the edges between two nodes.

        Use this when the line itself is the evidence: to read an edge's attributes, or to
        confirm whether two nodes are joined by one connection or by several parallel
        ones. Supply at least one endpoint; an unfiltered edge dump is refused.

        Args:
            path: Corpus-relative path to a .graphml file.
            source: One endpoint's identifier.
            target: The other endpoint's identifier.
            limit: Maximum edges to return.

        Returns:
            One edge per line with its attributes, plus the total match count and an
            explicit note when the returned set is truncated.
        """
        with instrument_tool(metrics, "graph_edge_lookup"):
            resolved = await asyncio.to_thread(_resolve, path)
            edges, total = await asyncio.to_thread(
                graphs.edge_lookup, resolved, source=source, target=target, limit=limit
            )
            metrics.observe("graph_query_edges_returned", float(len(edges)))
            return _render_edges(edges, total)

    return [
        graph_summary,
        graph_find_nodes,
        graph_neighbors,
        graph_connected_equipment,
        graph_shortest_path,
        graph_edge_lookup,
    ]


def _render_summary(path: str, summary: GraphSummary) -> str:
    """Render graph-level metadata as a tool result string."""
    orientation = "directed" if summary.directed else "undirected"
    parallel = "with parallel edges" if summary.multigraph else "without parallel edges"
    lines = [
        f"{path}: {orientation} graph {parallel}.",
        f"nodes={summary.node_count} edges={summary.edge_count} "
        f"isolated_nodes={summary.isolated_node_count}",
        f"node attributes: {_join(summary.node_attribute_keys)}",
        f"edge attributes: {_join(summary.edge_attribute_keys)}",
    ]
    if summary.label_histogram:
        rendered = ", ".join(f"{label}={count}" for label, count in summary.label_histogram)
        lines.append(f"node labels by frequency: {rendered}")
    else:
        lines.append("node labels by frequency: no 'label' attribute present on nodes")
    return "\n".join(lines)


def _render_search(query: str, result: SearchResult) -> str:
    """Render node-identity matches as a tool result string."""
    if result.total_matched == 0:
        return f"No node matches '{query}' by identifier or attribute value."
    lines = [f"{result.total_matched} node(s) match '{query}':"]
    lines.extend(node.render() for node in result.nodes)
    if result.truncated:
        lines.append(
            f"TRUNCATED: {result.total_matched - len(result.nodes)} further matches are not "
            "listed; narrow the query or raise the limit."
        )
    return "\n".join(lines)


def _render_neighborhood(result: NeighborhoodResult) -> str:
    """Render a bounded neighbourhood expansion as a tool result string."""
    lines = [
        f"Neighbourhood of '{result.origin}' within {result.hops} hop(s): "
        f"{len(result.nodes)} node(s), {len(result.edges)} edge(s)."
    ]
    lines.append("nodes:")
    lines.extend(
        f"  hop {result.distances.get(node.node_id, 0)} | {node.render()}" for node in result.nodes
    )
    if result.edges:
        lines.append("edges:")
        lines.extend(f"  {edge.render()}" for edge in result.edges)
    else:
        lines.append("edges: none among the reached nodes")
    if result.truncated:
        lines.append(f"TRUNCATED: {result.truncation_reason}")
    return "\n".join(lines)


def _render_equipment(result: EquipmentReach) -> str:
    """Render an apparatus walk as a tool result string."""
    walked = ", ".join(sorted(DRAFTING_LABELS))
    lines = [
        f"Equipment connected to '{result.origin}', walking through drafting apparatus "
        f"({walked}): {len(result.found)} item(s), via {result.apparatus_walked} apparatus node(s)."
    ]
    if result.found:
        lines.extend(
            f"  {hops} hop(s) | {node_id} [label={label}]" for node_id, label, hops in result.found
        )
    else:
        lines.append("  none: the node joins only drafting apparatus, or nothing")
    lines.append(
        "Each item is the first equipment on its path; anything beyond it is connected to "
        "that item, not to the origin."
    )
    if result.truncated:
        lines.append(f"TRUNCATED: {result.truncation_reason}")
    return "\n".join(lines)


def _render_path(result: PathResult) -> str:
    """Render a connection query as a tool result string."""
    mode = "respecting edge direction" if result.respects_direction else "ignoring direction"
    if not result.found:
        return (
            f"No path from '{result.source}' to '{result.target}' within {result.cutoff} "
            f"edge(s), {mode}. A longer path may exist beyond the cutoff."
        )
    lines = [
        f"Path from '{result.source}' to '{result.target}' has "
        f"{len(result.nodes) - 1} edge(s), {mode}.",
        "nodes: " + " -> ".join(result.nodes),
    ]
    if result.edges:
        lines.append("edges:")
        lines.extend(f"  {edge.render()}" for edge in result.edges)
    return "\n".join(lines)


def _render_edges(edges: tuple[EdgeRecord, ...], total: int) -> str:
    """Render an edge lookup as a tool result string."""
    if total == 0:
        return "No edge matches the requested endpoints."
    lines = [f"{total} edge(s) match:"]
    lines.extend(edge.render() for edge in edges)
    if total > len(edges):
        lines.append(
            f"TRUNCATED: {total - len(edges)} further edges are not listed; raise the limit "
            "or narrow the endpoints."
        )
    return "\n".join(lines)


def _join(values: tuple[str, ...]) -> str:
    """Render an attribute-name tuple, distinguishing empty from present."""
    return ", ".join(values) if values else "(none)"
