/**
 * The small artifacts a stage emits, generated as real files from the run's current state.
 *
 * Configuration, manifests and profiles are text a deployment actually consumes, so they are
 * produced here with the values the page shows. Model weights are not: a simulated run
 * trains none, and a download that pretended otherwise would be the one fabrication this
 * page must not make.
 */

import type { ArtifactSpec, Stage } from "./stages";

export interface GeneratedFile {
  readonly name: string;
  readonly type: string;
  readonly body: string;
}

export interface ArtifactContext {
  readonly stage: Stage;
  readonly step: number;
  readonly progress: number;
  readonly generatedAt: string;
  readonly sheet: string;
  readonly verifierPassRate: number;
  readonly samples: readonly {
    readonly tag: string;
    readonly overall: number;
    readonly pass: boolean;
  }[];
}

export function artifactFile(
  spec: ArtifactSpec,
  context: ArtifactContext,
): GeneratedFile | undefined {
  const { stage, step, generatedAt } = context;
  const provenance = {
    experiment: stage.experimentId,
    stage: `${stage.number} ${stage.title}`,
    step: Math.round(step),
    generated_at: generatedAt,
    run: "simulated",
    note: "Generated by the P&ID Intelligence model lab from a simulated run. No weights were trained.",
  };

  switch (spec.download) {
    case "manifest":
      return {
        name: stage.id === "sft" ? "tool-call-policy.yaml" : "inference-manifest.yaml",
        type: "application/yaml",
        body: [
          `# ${spec.title}`,
          `# ${provenance.note}`,
          `experiment: ${provenance.experiment}`,
          `stage: "${provenance.stage}"`,
          `step: ${provenance.step}`,
          `generated_at: ${generatedAt}`,
          "model:",
          `  name: ${stage.id === "distillation" ? "Qwen3-VL-8B-distill" : "Qwen3-VL-32B-sft"}`,
          "  context_length: " + (stage.id === "distillation" ? "32768" : "131072"),
          `  precision: ${stage.id === "distillation" ? "int8" : "bf16"}`,
          "tools:",
          "  - name: corpus_search",
          "  - name: load_corpus_artifact",
          "  - name: render_drawing_region",
          "  - name: graph_connected_equipment",
          "  - name: graph_neighbors",
          "grounding:",
          `  sheet: "${context.sheet}"`,
          "  require_citations: true",
          "  abstain_on_unverified: true",
          "",
        ].join("\n"),
      };
    case "serving-config":
      return {
        name: "tensorrt-llm-config.json",
        type: "application/json",
        body: JSON.stringify(
          {
            provenance,
            engine: {
              backend: "tensorrt-llm",
              quantization: { weights: "int8", kv_cache: "fp8" },
              max_batch_size: 8,
              max_input_len: 32768,
              max_output_len: 2048,
              tensor_parallel: 1,
            },
            target: {
              gpu: "L4 / L40S",
              memory_gb: 16,
              latency_target_s: 1.0,
              air_gapped: true,
            },
          },
          null,
          2,
        ),
      };
    case "profile":
      return {
        name: "plant-profile-v1.0.json",
        type: "application/json",
        body: JSON.stringify(
          {
            provenance,
            plant: { sheet: context.sheet },
            policy: {
              verifier_pass_threshold: 0.7,
              require_pid_citation: true,
              abstain_below_verifier_score: 0.55,
            },
            observed: {
              verifier_pass_rate: Number(context.verifierPassRate.toFixed(3)),
              samples: context.samples,
            },
          },
          null,
          2,
        ),
      };
    case "behavior-profile":
      return {
        name: "behavior-profile-v1.0.json",
        type: "application/json",
        body: JSON.stringify(
          {
            provenance,
            reward_weights: Object.fromEntries(
              (stage.rewards ?? []).map((r) => [r.name, r.weight]),
            ),
            verifier: {
              pass_threshold: 0.7,
              observed_pass_rate: Number(context.verifierPassRate.toFixed(3)),
              samples: context.samples,
            },
          },
          null,
          2,
        ),
      };
    default:
      return undefined;
  }
}
